version: "3"
services:
  xdebug:
    container_name: xdebug
    build:
      context: docker/php/
    environment:
      PHP_IDE_CONFIG: 'serverName=host.docker.internal'
      XDEBUG_TRIGGER: 1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/app
    tty: true